"""add_widget_width_height_columns

Revision ID: 0b1c190586ca
Revises: bbad2f7b3a46
Create Date: 2025-12-20 18:21:48.126915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b1c190586ca'
down_revision: Union[str, Sequence[str], None] = 'bbad2f7b3a46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('widget_settings', sa.Column('widget_width', sa.Integer(), nullable=True))
    op.add_column('widget_settings', sa.Column('widget_height', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('widget_settings', 'widget_height')
    op.drop_column('widget_settings', 'widget_width')
    # ### end Alembic commands ###
