"""add_summary_fields_to_conversation_sessions

Revision ID: 0f15934286af
Revises: 30df1bf12509
Create Date: 2025-12-25 17:41:36.763145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f15934286af'
down_revision: Union[str, Sequence[str], None] = '30df1bf12509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_sessions', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('conversation_sessions', sa.Column('summary_generated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_sessions', 'summary_generated_at')
    op.drop_column('conversation_sessions', 'summary')
    # ### end Alembic commands ###
