"""Add handoff_team_id to agents

Revision ID: 14adb0b61ef9
Revises: 20c788f7449d
Create Date: 2025-11-14 22:53:50.048666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14adb0b61ef9'
down_revision: Union[str, Sequence[str], None] = '20c788f7449d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('handoff_team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'agents', 'teams', ['handoff_team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_column('agents', 'handoff_team_id')
    # ### end Alembic commands ###
