"""AI tools initial models added

Revision ID: 1a5ab279ca1a
Revises: c81638d07ff2
Create Date: 2025-09-21 00:00:14.016437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a5ab279ca1a'
down_revision: Union[str, Sequence[str], None] = 'c81638d07ff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_tool_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_tool_categories_id'), 'ai_tool_categories', ['id'], unique=False)
    op.create_index(op.f('ix_ai_tool_categories_name'), 'ai_tool_categories', ['name'], unique=True)
    op.create_table('ai_tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['ai_tool_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_tools_id'), 'ai_tools', ['id'], unique=False)
    op.create_index(op.f('ix_ai_tools_name'), 'ai_tools', ['name'], unique=False)
    op.create_table('ai_tool_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=True),
    sa.Column('question_text', sa.String(), nullable=True),
    sa.Column('question_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tool_id'], ['ai_tools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_tool_questions_id'), 'ai_tool_questions', ['id'], unique=False)
    op.create_table('ai_tool_favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ai_tool_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ai_tool_id'], ['ai_tools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'ai_tool_id')
    )
    op.drop_index(op.f('ix_optimization_suggestions_id'), table_name='optimization_suggestions')
    op.drop_table('optimization_suggestions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('optimization_suggestions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('suggestion_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('optimization_suggestions_agent_id_fkey')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('optimization_suggestions_company_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('optimization_suggestions_pkey'))
    )
    op.create_index(op.f('ix_optimization_suggestions_id'), 'optimization_suggestions', ['id'], unique=False)
    op.drop_table('ai_tool_favorites')
    op.drop_index(op.f('ix_ai_tool_questions_id'), table_name='ai_tool_questions')
    op.drop_table('ai_tool_questions')
    op.drop_index(op.f('ix_ai_tools_name'), table_name='ai_tools')
    op.drop_index(op.f('ix_ai_tools_id'), table_name='ai_tools')
    op.drop_table('ai_tools')
    op.drop_index(op.f('ix_ai_tool_categories_name'), table_name='ai_tool_categories')
    op.drop_index(op.f('ix_ai_tool_categories_id'), table_name='ai_tool_categories')
    op.drop_table('ai_tool_categories')
    # ### end Alembic commands ###
