"""Migrate to team-based agent pool management

Revision ID: 20c788f7449d
Revises: efb472d9be62
Create Date: 2025-11-14 22:26:40.547192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20c788f7449d'
down_revision: Union[str, Sequence[str], None] = 'efb472d9be62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_pools_company_id'), table_name='agent_pools')
    op.drop_index(op.f('ix_agent_pools_id'), table_name='agent_pools')
    op.drop_index(op.f('ix_agent_pools_pool_name'), table_name='agent_pools')
    op.drop_index(op.f('ix_agent_pools_user_id'), table_name='agent_pools')
    op.drop_table('agent_pools')
    op.add_column('team_memberships', sa.Column('is_available', sa.Boolean(), server_default='true', nullable=True))
    op.add_column('team_memberships', sa.Column('priority', sa.Integer(), server_default='0', nullable=True))
    op.add_column('team_memberships', sa.Column('max_concurrent_sessions', sa.Integer(), server_default='3', nullable=True))
    op.add_column('team_memberships', sa.Column('current_session_count', sa.Integer(), server_default='0', nullable=True))
    op.add_column('team_memberships', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('team_memberships', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_memberships', 'updated_at')
    op.drop_column('team_memberships', 'created_at')
    op.drop_column('team_memberships', 'current_session_count')
    op.drop_column('team_memberships', 'max_concurrent_sessions')
    op.drop_column('team_memberships', 'priority')
    op.drop_column('team_memberships', 'is_available')
    op.create_table('agent_pools',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pool_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('max_concurrent_sessions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_session_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('agent_pools_company_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('agent_pools_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_pools_pkey'))
    )
    op.create_index(op.f('ix_agent_pools_user_id'), 'agent_pools', ['user_id'], unique=False)
    op.create_index(op.f('ix_agent_pools_pool_name'), 'agent_pools', ['pool_name'], unique=False)
    op.create_index(op.f('ix_agent_pools_id'), 'agent_pools', ['id'], unique=False)
    op.create_index(op.f('ix_agent_pools_company_id'), 'agent_pools', ['company_id'], unique=False)
    # ### end Alembic commands ###
