"""Add options column to chat_messages

Revision ID: 30df1bf12509
Revises: 0b1c190586ca
Create Date: 2025-12-24 00:27:01.134305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30df1bf12509'
down_revision: Union[str, Sequence[str], None] = '0b1c190586ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('options', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'options')
    # ### end Alembic commands ###
