"""add_agent_id_and_is_active_to_published_widget_settings

Revision ID: 5bc261b566b8
Revises: 0f15934286af
Create Date: 2025-12-26 00:09:48.189116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bc261b566b8'
down_revision: Union[str, Sequence[str], None] = '0f15934286af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('published_widget_settings', sa.Column('agent_id', sa.Integer(), nullable=True))
    op.add_column('published_widget_settings', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('published_widget_settings', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('published_widget_settings', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_published_widget_settings_agent_id'), 'published_widget_settings', ['agent_id'], unique=True)
    op.create_foreign_key(None, 'published_widget_settings', 'agents', ['agent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'published_widget_settings', type_='foreignkey')
    op.drop_index(op.f('ix_published_widget_settings_agent_id'), table_name='published_widget_settings')
    op.drop_column('published_widget_settings', 'updated_at')
    op.drop_column('published_widget_settings', 'created_at')
    op.drop_column('published_widget_settings', 'is_active')
    op.drop_column('published_widget_settings', 'agent_id')
    # ### end Alembic commands ###
