"""base models

Revision ID: 607d3abad39f
Revises: 
Create Date: 2025-12-11 11:46:01.408974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '607d3abad39f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('generation_params', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_images_id'), 'ai_images', ['id'], unique=False)
    op.create_table('ai_tool_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_tool_categories_id'), 'ai_tool_categories', ['id'], unique=False)
    op.create_index(op.f('ix_ai_tool_categories_name'), 'ai_tool_categories', ['name'], unique=True)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('published_widget_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publish_id', sa.String(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_published_widget_settings_id'), 'published_widget_settings', ['id'], unique=False)
    op.create_index(op.f('ix_published_widget_settings_publish_id'), 'published_widget_settings', ['publish_id'], unique=True)
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('features', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plans_id'), 'subscription_plans', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_plans_name'), 'subscription_plans', ['name'], unique=True)
    op.create_table('temporary_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temporary_documents_document_id'), 'temporary_documents', ['document_id'], unique=True)
    op.create_index(op.f('ix_temporary_documents_id'), 'temporary_documents', ['id'], unique=False)
    op.create_table('ai_tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['ai_tool_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_tools_id'), 'ai_tools', ['id'], unique=False)
    op.create_index(op.f('ix_ai_tools_name'), 'ai_tools', ['name'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_key'), 'api_keys', ['key'], unique=True)
    op.create_table('company_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('support_email', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('business_hours', sa.Boolean(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('primary_color', sa.String(), nullable=True),
    sa.Column('secondary_color', sa.String(), nullable=True),
    sa.Column('custom_domain', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('smtp_host', sa.String(), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_user', sa.String(), nullable=True),
    sa.Column('smtp_password', sa.Text(), nullable=True),
    sa.Column('smtp_use_tls', sa.Boolean(), nullable=True),
    sa.Column('smtp_from_email', sa.String(), nullable=True),
    sa.Column('smtp_from_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_settings_id'), 'company_settings', ['id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('custom_attributes', sa.JSON(), nullable=True),
    sa.Column('lead_source', sa.String(), nullable=True),
    sa.Column('lifecycle_stage', sa.Enum('SUBSCRIBER', 'LEAD', 'MQL', 'SQL', 'OPPORTUNITY', 'CUSTOMER', 'EVANGELIST', 'OTHER', name='lifecyclestage'), nullable=True),
    sa.Column('do_not_contact', sa.Boolean(), nullable=False),
    sa.Column('opt_in_status', sa.Enum('OPTED_IN', 'OPTED_OUT', 'PENDING', 'UNKNOWN', name='optinstatus'), nullable=False),
    sa.Column('opt_in_date', sa.DateTime(), nullable=True),
    sa.Column('opt_out_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=True)
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_index(op.f('ix_contacts_lead_source'), 'contacts', ['lead_source'], unique=False)
    op.create_index(op.f('ix_contacts_lifecycle_stage'), 'contacts', ['lifecycle_stage'], unique=False)
    op.create_index(op.f('ix_contacts_name'), 'contacts', ['name'], unique=False)
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('encrypted_credentials', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credentials_id'), 'credentials', ['id'], unique=False)
    op.create_index(op.f('ix_credentials_name'), 'credentials', ['name'], unique=False)
    op.create_index(op.f('ix_credentials_service'), 'credentials', ['service'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('validation_regex', sa.String(length=500), nullable=True),
    sa.Column('example_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_id'), 'entities', ['id'], unique=False)
    op.create_table('integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('credentials', sa.String(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrations_id'), 'integrations', ['id'], unique=False)
    op.create_index(op.f('ix_integrations_type'), 'integrations', ['type'], unique=False)
    op.create_table('knowledge_bases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('connection_details', sa.JSON(), nullable=True),
    sa.Column('storage_type', sa.String(), nullable=True),
    sa.Column('storage_details', sa.JSON(), nullable=True),
    sa.Column('chroma_collection_name', sa.String(), nullable=True),
    sa.Column('faiss_index_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chroma_collection_name')
    )
    op.create_index(op.f('ix_knowledge_bases_id'), 'knowledge_bases', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_bases_name'), 'knowledge_bases', ['name'], unique=False)
    op.create_table('notification_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('email_notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('slack_notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('auto_assignment_enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_settings_id'), 'notification_settings', ['id'], unique=False)
    op.create_table('processing_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_templates_id'), 'processing_templates', ['id'], unique=False)
    op.create_index(op.f('ix_processing_templates_name'), 'processing_templates', ['name'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_role_name_per_company')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'company_id', name='uq_tag_name_company')
    )
    op.create_index(op.f('ix_tags_company_id'), 'tags', ['company_id'], unique=False)
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=True)
    op.create_table('tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('tool_type', sa.String(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('mcp_server_url', sa.String(), nullable=True),
    sa.Column('is_pre_built', sa.Boolean(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('follow_up_config', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tools_id'), 'tools', ['id'], unique=False)
    op.create_index(op.f('ix_tools_name'), 'tools', ['name'], unique=False)
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('welcome_message', sa.String(), nullable=True),
    sa.Column('prompt', sa.String(), nullable=True),
    sa.Column('llm_provider', sa.String(), nullable=True),
    sa.Column('embedding_model', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('personality', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('response_style', sa.String(), nullable=True),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.Column('credential_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('handoff_team_id', sa.Integer(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('parent_version_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('voice_id', sa.String(), nullable=True),
    sa.Column('tts_provider', sa.String(), nullable=False),
    sa.Column('stt_provider', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ),
    sa.ForeignKeyConstraint(['handoff_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['parent_version_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)
    op.create_index(op.f('ix_agents_name'), 'agents', ['name'], unique=False)
    op.create_table('ai_tool_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=True),
    sa.Column('question_text', sa.String(), nullable=True),
    sa.Column('question_type', sa.String(), nullable=True),
    sa.Column('hint', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tool_id'], ['ai_tools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_tool_questions_id'), 'ai_tool_questions', ['id'], unique=False)
    op.create_table('contact_tags',
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contact_id', 'tag_id')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('profile_picture_url', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('subscription_plan_id', sa.Integer(), nullable=True),
    sa.Column('subscription_status', sa.String(), nullable=True),
    sa.Column('subscription_start_date', sa.DateTime(), nullable=True),
    sa.Column('subscription_end_date', sa.DateTime(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_super_admin', sa.Boolean(), nullable=True),
    sa.Column('presence_status', sa.String(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('agent_knowledge_bases',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('agent_id', 'knowledge_base_id')
    )
    op.create_table('agent_tools',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('agent_id', 'tool_id')
    )
    op.create_table('ai_tool_favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ai_tool_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ai_tool_id'], ['ai_tools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'ai_tool_id')
    )
    op.create_table('chat_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('channel_type', sa.Enum('TEAM', 'DM', name='channeltype'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_channels_id'), 'chat_channels', ['id'], unique=False)
    op.create_table('conversation_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=255), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.Column('added_by_user_id', sa.Integer(), nullable=True),
    sa.Column('added_by_system', sa.Boolean(), nullable=True),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_tags_conversation_id'), 'conversation_tags', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_tags_id'), 'conversation_tags', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_tags_tag'), 'conversation_tags', ['tag'], unique=False)
    op.create_table('memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_id'), 'memories', ['id'], unique=False)
    op.create_index(op.f('ix_memories_key'), 'memories', ['key'], unique=False)
    op.create_index(op.f('ix_memories_session_id'), 'memories', ['session_id'], unique=False)
    op.create_table('message_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('shortcut', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('scope', sa.Enum('PERSONAL', 'SHARED', name='templatescope'), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_templates_company_id'), 'message_templates', ['company_id'], unique=False)
    op.create_index(op.f('ix_message_templates_created_by_user_id'), 'message_templates', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_message_templates_id'), 'message_templates', ['id'], unique=False)
    op.create_index(op.f('ix_message_templates_scope'), 'message_templates', ['scope'], unique=False)
    op.create_index(op.f('ix_message_templates_shortcut'), 'message_templates', ['shortcut'], unique=False)
    op.create_table('optimization_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suggestion_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_suggestions_id'), 'optimization_suggestions', ['id'], unique=False)
    op.create_table('segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('segment_type', sa.Enum('DYNAMIC', 'STATIC', name='segmenttype'), nullable=False),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('static_contact_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('static_lead_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contact_count', sa.Integer(), nullable=False),
    sa.Column('lead_count', sa.Integer(), nullable=False),
    sa.Column('last_refreshed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segments_company_id'), 'segments', ['company_id'], unique=False)
    op.create_index(op.f('ix_segments_id'), 'segments', ['id'], unique=False)
    op.create_index(op.f('ix_segments_name'), 'segments', ['name'], unique=False)
    op.create_table('team_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('is_available', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('priority', sa.Integer(), server_default='0', nullable=True),
    sa.Column('max_concurrent_sessions', sa.Integer(), server_default='3', nullable=True),
    sa.Column('current_session_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_memberships_id'), 'team_memberships', ['id'], unique=False)
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_type', sa.Enum('EMAIL', 'SMS', 'WHATSAPP', 'VOICE', name='templatetype'), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('html_body', sa.Text(), nullable=True),
    sa.Column('voice_script', sa.Text(), nullable=True),
    sa.Column('tts_voice_id', sa.String(length=100), nullable=True),
    sa.Column('whatsapp_template_name', sa.String(length=255), nullable=True),
    sa.Column('whatsapp_template_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('personalization_tokens', postgresql.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_company_id'), 'templates', ['company_id'], unique=False)
    op.create_index(op.f('ix_templates_id'), 'templates', ['id'], unique=False)
    op.create_index(op.f('ix_templates_template_type'), 'templates', ['template_type'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('dark_mode', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=False)
    op.create_table('voice_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider_voice_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_profiles_id'), 'voice_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_voice_profiles_name'), 'voice_profiles', ['name'], unique=False)
    op.create_index(op.f('ix_voice_profiles_provider_voice_id'), 'voice_profiles', ['provider_voice_id'], unique=True)
    op.create_table('webhooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('trigger_event', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhooks_id'), 'webhooks', ['id'], unique=False)
    op.create_index(op.f('ix_webhooks_name'), 'webhooks', ['name'], unique=False)
    op.create_table('widget_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primary_color', sa.String(), nullable=True),
    sa.Column('header_title', sa.String(), nullable=True),
    sa.Column('welcome_message', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('border_radius', sa.Integer(), nullable=True),
    sa.Column('font_family', sa.String(), nullable=True),
    sa.Column('agent_avatar_url', sa.String(), nullable=True),
    sa.Column('input_placeholder', sa.String(), nullable=True),
    sa.Column('user_message_color', sa.String(), nullable=True),
    sa.Column('user_message_text_color', sa.String(), nullable=True),
    sa.Column('bot_message_color', sa.String(), nullable=True),
    sa.Column('bot_message_text_color', sa.String(), nullable=True),
    sa.Column('time_color', sa.String(), nullable=True),
    sa.Column('widget_size', sa.String(), nullable=True),
    sa.Column('show_header', sa.Boolean(), nullable=True),
    sa.Column('livekit_url', sa.String(), nullable=True),
    sa.Column('frontend_url', sa.String(), nullable=True),
    sa.Column('proactive_message_enabled', sa.Boolean(), nullable=True),
    sa.Column('proactive_message', sa.String(), nullable=True),
    sa.Column('proactive_message_delay', sa.Integer(), nullable=True),
    sa.Column('suggestions_enabled', sa.Boolean(), nullable=True),
    sa.Column('dark_mode', sa.Boolean(), nullable=True),
    sa.Column('typing_indicator_enabled', sa.Boolean(), nullable=True),
    sa.Column('communication_mode', sa.String(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_widget_settings_id'), 'widget_settings', ['id'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('visual_steps', sa.JSON(), nullable=True),
    sa.Column('trigger_phrases', sa.JSON(), nullable=True),
    sa.Column('intent_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('parent_workflow_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['parent_workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_id'), 'workflows', ['id'], unique=False)
    op.create_index(op.f('ix_workflows_name'), 'workflows', ['name'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('campaign_type', sa.Enum('EMAIL', 'SMS', 'WHATSAPP', 'VOICE', 'MULTI_CHANNEL', name='campaigntype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'ACTIVE', 'PAUSED', 'COMPLETED', 'ARCHIVED', name='campaignstatus'), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('scheduled_send_time', sa.DateTime(), nullable=True),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('target_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('goal_type', sa.Enum('LEAD_GENERATION', 'NURTURE', 'CONVERSION', 'ENGAGEMENT', 'RETENTION', 'REACTIVATION', name='goaltype'), nullable=True),
    sa.Column('goal_value', sa.Integer(), nullable=True),
    sa.Column('budget', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('actual_cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('twilio_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_contacts', sa.Integer(), nullable=False),
    sa.Column('contacts_reached', sa.Integer(), nullable=False),
    sa.Column('contacts_engaged', sa.Integer(), nullable=False),
    sa.Column('contacts_converted', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_campaign_type'), 'campaigns', ['campaign_type'], unique=False)
    op.create_index(op.f('ix_campaigns_company_id'), 'campaigns', ['company_id'], unique=False)
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_index(op.f('ix_campaigns_name'), 'campaigns', ['name'], unique=False)
    op.create_index(op.f('ix_campaigns_segment_id'), 'campaigns', ['segment_id'], unique=False)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_table('channel_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['chat_channels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_memberships_id'), 'channel_memberships', ['id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('workflow_node_id', sa.String(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_table('conversation_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('next_step_id', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_ai_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_client_connected', sa.Boolean(), nullable=False),
    sa.Column('reopen_count', sa.Integer(), nullable=False),
    sa.Column('last_reopened_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('handoff_requested_at', sa.DateTime(), nullable=True),
    sa.Column('handoff_reason', sa.String(), nullable=True),
    sa.Column('assigned_pool', sa.String(), nullable=True),
    sa.Column('waiting_for_agent', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('handoff_accepted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_sessions_conversation_id'), 'conversation_sessions', ['conversation_id'], unique=True)
    op.create_index(op.f('ix_conversation_sessions_id'), 'conversation_sessions', ['id'], unique=False)
    op.create_table('intents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('intent_category', sa.String(length=50), nullable=True),
    sa.Column('training_phrases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trigger_workflow_id', sa.Integer(), nullable=True),
    sa.Column('auto_trigger_enabled', sa.Boolean(), nullable=True),
    sa.Column('require_agent_approval', sa.Boolean(), nullable=True),
    sa.Column('confidence_threshold', sa.Float(), nullable=True),
    sa.Column('min_confidence_auto_trigger', sa.Float(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['trigger_workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intents_id'), 'intents', ['id'], unique=False)
    op.create_table('internal_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('parent_message_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['chat_channels.id'], ),
    sa.ForeignKeyConstraint(['parent_message_id'], ['internal_chat_messages.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_chat_messages_id'), 'internal_chat_messages', ['id'], unique=False)
    op.create_table('video_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('invited_users', sa.JSON(), nullable=True),
    sa.Column('joined_users', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('participants', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['chat_channels.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_calls_id'), 'video_calls', ['id'], unique=False)
    op.create_index(op.f('ix_video_calls_room_name'), 'video_calls', ['room_name'], unique=True)
    op.create_table('workflow_triggers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('WEBSOCKET', 'WHATSAPP', 'TELEGRAM', 'INSTAGRAM', name='triggerchannel'), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('fallback_agent_id', sa.Integer(), nullable=True),
    sa.Column('auto_respond', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['fallback_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_triggers_channel'), 'workflow_triggers', ['channel'], unique=False)
    op.create_index(op.f('ix_workflow_triggers_id'), 'workflow_triggers', ['id'], unique=False)
    op.create_table('campaign_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('message_type', sa.Enum('EMAIL', 'SMS', 'WHATSAPP', 'INSTAGRAM', 'TELEGRAM', 'VOICE', 'AI_CONVERSATION', name='messagetype'), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('html_body', sa.Text(), nullable=True),
    sa.Column('voice_script', sa.Text(), nullable=True),
    sa.Column('tts_voice_id', sa.String(), nullable=True),
    sa.Column('voice_agent_id', sa.Integer(), nullable=True),
    sa.Column('twilio_phone_number', sa.String(), nullable=True),
    sa.Column('call_flow_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('whatsapp_template_name', sa.String(), nullable=True),
    sa.Column('whatsapp_template_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('delay_amount', sa.Integer(), nullable=False),
    sa.Column('delay_unit', sa.Enum('MINUTES', 'HOURS', 'DAYS', 'WEEKS', name='delayunit'), nullable=False),
    sa.Column('send_time_window_start', sa.String(), nullable=True),
    sa.Column('send_time_window_end', sa.String(), nullable=True),
    sa.Column('send_on_weekdays_only', sa.Boolean(), nullable=False),
    sa.Column('is_ab_test', sa.Boolean(), nullable=False),
    sa.Column('ab_variant', sa.String(), nullable=True),
    sa.Column('ab_split_percentage', sa.Integer(), nullable=True),
    sa.Column('personalization_tokens', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cta_text', sa.String(), nullable=True),
    sa.Column('cta_url', sa.String(), nullable=True),
    sa.Column('track_clicks', sa.Boolean(), nullable=False),
    sa.Column('send_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.ForeignKeyConstraint(['voice_agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_messages_campaign_id'), 'campaign_messages', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_messages_id'), 'campaign_messages', ['id'], unique=False)
    op.create_table('chat_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['internal_chat_messages.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_attachments_id'), 'chat_attachments', ['id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('message_type', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('feedback_rating', sa.Integer(), nullable=True),
    sa.Column('feedback_notes', sa.String(), nullable=True),
    sa.Column('issue', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_issue'), 'chat_messages', ['issue'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('intent_entities',
    sa.Column('intent_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['intent_id'], ['intents.id'], ),
    sa.PrimaryKeyConstraint('intent_id', 'entity_id')
    )
    op.create_table('intent_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=255), nullable=False),
    sa.Column('intent_id', sa.Integer(), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('matched_method', sa.String(length=50), nullable=True),
    sa.Column('extracted_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('triggered_workflow_id', sa.Integer(), nullable=True),
    sa.Column('workflow_executed', sa.Boolean(), nullable=True),
    sa.Column('execution_status', sa.String(length=50), nullable=True),
    sa.Column('matched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['intent_id'], ['intents.id'], ),
    sa.ForeignKeyConstraint(['triggered_workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intent_matches_conversation_id'), 'intent_matches', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_intent_matches_id'), 'intent_matches', ['id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.Enum('LEAD', 'MQL', 'SQL', 'OPPORTUNITY', 'CUSTOMER', 'LOST', name='leadstage'), nullable=False),
    sa.Column('stage_changed_at', sa.DateTime(), nullable=False),
    sa.Column('previous_stage', sa.Enum('LEAD', 'MQL', 'SQL', 'OPPORTUNITY', 'CUSTOMER', 'LOST', name='leadstage'), nullable=True),
    sa.Column('qualification_status', sa.Enum('UNQUALIFIED', 'IN_PROGRESS', 'QUALIFIED', 'DISQUALIFIED', name='qualificationstatus'), nullable=False),
    sa.Column('qualification_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('last_scored_at', sa.DateTime(), nullable=True),
    sa.Column('deal_value', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('expected_close_date', sa.DateTime(), nullable=True),
    sa.Column('actual_close_date', sa.DateTime(), nullable=True),
    sa.Column('won_reason', sa.String(), nullable=True),
    sa.Column('lost_reason', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_assignee_id'), 'leads', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_leads_campaign_id'), 'leads', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_leads_company_id'), 'leads', ['company_id'], unique=False)
    op.create_index(op.f('ix_leads_contact_id'), 'leads', ['contact_id'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_score'), 'leads', ['score'], unique=False)
    op.create_index(op.f('ix_leads_source'), 'leads', ['source'], unique=False)
    op.create_index(op.f('ix_leads_stage'), 'leads', ['stage'], unique=False)
    op.create_table('message_mentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('mentioned_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['mentioned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['internal_chat_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_mentions_id'), 'message_mentions', ['id'], unique=False)
    op.create_table('message_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['internal_chat_messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', 'emoji', name='unique_message_user_emoji')
    )
    op.create_index(op.f('ix_message_reactions_id'), 'message_reactions', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('related_message_id', sa.Integer(), nullable=True),
    sa.Column('related_channel_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['related_channel_id'], ['chat_channels.id'], ),
    sa.ForeignKeyConstraint(['related_message_id'], ['internal_chat_messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('campaign_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.Enum('EMAIL_SENT', 'EMAIL_DELIVERED', 'EMAIL_OPENED', 'EMAIL_CLICKED', 'EMAIL_REPLIED', 'EMAIL_BOUNCED', 'EMAIL_UNSUBSCRIBED', 'SMS_SENT', 'SMS_DELIVERED', 'SMS_REPLIED', 'SMS_FAILED', 'WHATSAPP_SENT', 'WHATSAPP_DELIVERED', 'WHATSAPP_READ', 'WHATSAPP_REPLIED', 'CALL_INITIATED', 'CALL_RINGING', 'CALL_ANSWERED', 'CALL_COMPLETED', 'CALL_FAILED', 'CALL_BUSY', 'CALL_NO_ANSWER', 'VOICEMAIL_DETECTED', 'VOICEMAIL_LEFT', 'CONVERSATION_STARTED', 'CONVERSATION_REPLIED', 'CONVERSATION_ENDED', 'FORM_SUBMITTED', 'MEETING_BOOKED', 'LEAD_QUALIFIED', 'OPPORTUNITY_CREATED', 'DEAL_WON', 'DEAL_LOST', 'LINK_CLICKED', 'CONTENT_VIEWED', 'DOCUMENT_DOWNLOADED', 'OPTED_OUT', 'ERROR', name='activitytype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('activity_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('revenue_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['campaign_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_activities_activity_type'), 'campaign_activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_campaign_activities_campaign_id'), 'campaign_activities', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_activities_contact_id'), 'campaign_activities', ['contact_id'], unique=False)
    op.create_index(op.f('ix_campaign_activities_external_id'), 'campaign_activities', ['external_id'], unique=False)
    op.create_index(op.f('ix_campaign_activities_id'), 'campaign_activities', ['id'], unique=False)
    op.create_index(op.f('ix_campaign_activities_lead_id'), 'campaign_activities', ['lead_id'], unique=False)
    op.create_index(op.f('ix_campaign_activities_message_id'), 'campaign_activities', ['message_id'], unique=False)
    op.create_index(op.f('ix_campaign_activities_session_id'), 'campaign_activities', ['session_id'], unique=False)
    op.create_index(op.f('ix_campaign_activities_timestamp'), 'campaign_activities', ['timestamp'], unique=False)
    op.create_table('campaign_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(), nullable=False),
    sa.Column('enrolled_by_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'COMPLETED', 'OPTED_OUT', 'BOUNCED', 'FAILED', 'PAUSED', name='enrollmentstatus'), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('current_message_id', sa.Integer(), nullable=True),
    sa.Column('next_scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('last_interaction_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('opted_out_at', sa.DateTime(), nullable=True),
    sa.Column('opt_out_reason', sa.String(), nullable=True),
    sa.Column('opens', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('replies', sa.Integer(), nullable=False),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('calls_initiated', sa.Integer(), nullable=False),
    sa.Column('calls_completed', sa.Integer(), nullable=False),
    sa.Column('total_call_duration', sa.Integer(), nullable=False),
    sa.Column('voicemails_left', sa.Integer(), nullable=False),
    sa.Column('enrollment_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['current_message_id'], ['campaign_messages.id'], ),
    sa.ForeignKeyConstraint(['enrolled_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'contact_id', name='uq_campaign_contact')
    )
    op.create_index(op.f('ix_campaign_contacts_campaign_id'), 'campaign_contacts', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_contacts_contact_id'), 'campaign_contacts', ['contact_id'], unique=False)
    op.create_index(op.f('ix_campaign_contacts_id'), 'campaign_contacts', ['id'], unique=False)
    op.create_index(op.f('ix_campaign_contacts_lead_id'), 'campaign_contacts', ['lead_id'], unique=False)
    op.create_index(op.f('ix_campaign_contacts_status'), 'campaign_contacts', ['status'], unique=False)
    op.create_table('entity_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('note_type', sa.Enum('NOTE', 'CALL', 'MEETING', 'EMAIL', 'TASK', name='notetype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('activity_date', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('participants', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('outcome', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_notes_company_id'), 'entity_notes', ['company_id'], unique=False)
    op.create_index(op.f('ix_entity_notes_contact_id'), 'entity_notes', ['contact_id'], unique=False)
    op.create_index(op.f('ix_entity_notes_created_by'), 'entity_notes', ['created_by'], unique=False)
    op.create_index(op.f('ix_entity_notes_id'), 'entity_notes', ['id'], unique=False)
    op.create_index(op.f('ix_entity_notes_lead_id'), 'entity_notes', ['lead_id'], unique=False)
    op.create_index(op.f('ix_entity_notes_note_type'), 'entity_notes', ['note_type'], unique=False)
    op.create_table('lead_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('score_type', sa.Enum('AI_INTENT', 'ENGAGEMENT', 'DEMOGRAPHIC', 'BEHAVIORAL', 'WORKFLOW', 'MANUAL', 'COMBINED', name='scoretype'), nullable=False),
    sa.Column('score_value', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('score_reason', sa.Text(), nullable=True),
    sa.Column('score_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('intent_matches', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scored_by_user_id', sa.Integer(), nullable=True),
    sa.Column('scored_by_agent_id', sa.Integer(), nullable=True),
    sa.Column('conversation_session_id', sa.String(), nullable=True),
    sa.Column('scored_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('score_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['scored_by_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['scored_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_scores_company_id'), 'lead_scores', ['company_id'], unique=False)
    op.create_index(op.f('ix_lead_scores_id'), 'lead_scores', ['id'], unique=False)
    op.create_index(op.f('ix_lead_scores_lead_id'), 'lead_scores', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_scores_score_type'), 'lead_scores', ['score_type'], unique=False)
    op.create_index(op.f('ix_lead_scores_scored_at'), 'lead_scores', ['scored_at'], unique=False)
    op.create_table('lead_tags',
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lead_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead_tags')
    op.drop_index(op.f('ix_lead_scores_scored_at'), table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_score_type'), table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_lead_id'), table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_id'), table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_company_id'), table_name='lead_scores')
    op.drop_table('lead_scores')
    op.drop_index(op.f('ix_entity_notes_note_type'), table_name='entity_notes')
    op.drop_index(op.f('ix_entity_notes_lead_id'), table_name='entity_notes')
    op.drop_index(op.f('ix_entity_notes_id'), table_name='entity_notes')
    op.drop_index(op.f('ix_entity_notes_created_by'), table_name='entity_notes')
    op.drop_index(op.f('ix_entity_notes_contact_id'), table_name='entity_notes')
    op.drop_index(op.f('ix_entity_notes_company_id'), table_name='entity_notes')
    op.drop_table('entity_notes')
    op.drop_index(op.f('ix_campaign_contacts_status'), table_name='campaign_contacts')
    op.drop_index(op.f('ix_campaign_contacts_lead_id'), table_name='campaign_contacts')
    op.drop_index(op.f('ix_campaign_contacts_id'), table_name='campaign_contacts')
    op.drop_index(op.f('ix_campaign_contacts_contact_id'), table_name='campaign_contacts')
    op.drop_index(op.f('ix_campaign_contacts_campaign_id'), table_name='campaign_contacts')
    op.drop_table('campaign_contacts')
    op.drop_index(op.f('ix_campaign_activities_timestamp'), table_name='campaign_activities')
    op.drop_index(op.f('ix_campaign_activities_session_id'), table_name='campaign_activities')
    op.drop_index(op.f('ix_campaign_activities_message_id'), table_name='campaign_activities')
    op.drop_index(op.f('ix_campaign_activities_lead_id'), table_name='campaign_activities')
    op.drop_index(op.f('ix_campaign_activities_id'), table_name='campaign_activities')
    op.drop_index(op.f('ix_campaign_activities_external_id'), table_name='campaign_activities')
    op.drop_index(op.f('ix_campaign_activities_contact_id'), table_name='campaign_activities')
    op.drop_index(op.f('ix_campaign_activities_campaign_id'), table_name='campaign_activities')
    op.drop_index(op.f('ix_campaign_activities_activity_type'), table_name='campaign_activities')
    op.drop_table('campaign_activities')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_message_reactions_id'), table_name='message_reactions')
    op.drop_table('message_reactions')
    op.drop_index(op.f('ix_message_mentions_id'), table_name='message_mentions')
    op.drop_table('message_mentions')
    op.drop_index(op.f('ix_leads_stage'), table_name='leads')
    op.drop_index(op.f('ix_leads_source'), table_name='leads')
    op.drop_index(op.f('ix_leads_score'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_contact_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_company_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_campaign_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_assignee_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_intent_matches_id'), table_name='intent_matches')
    op.drop_index(op.f('ix_intent_matches_conversation_id'), table_name='intent_matches')
    op.drop_table('intent_matches')
    op.drop_table('intent_entities')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_issue'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_attachments_id'), table_name='chat_attachments')
    op.drop_table('chat_attachments')
    op.drop_index(op.f('ix_campaign_messages_id'), table_name='campaign_messages')
    op.drop_index(op.f('ix_campaign_messages_campaign_id'), table_name='campaign_messages')
    op.drop_table('campaign_messages')
    op.drop_index(op.f('ix_workflow_triggers_id'), table_name='workflow_triggers')
    op.drop_index(op.f('ix_workflow_triggers_channel'), table_name='workflow_triggers')
    op.drop_table('workflow_triggers')
    op.drop_index(op.f('ix_video_calls_room_name'), table_name='video_calls')
    op.drop_index(op.f('ix_video_calls_id'), table_name='video_calls')
    op.drop_table('video_calls')
    op.drop_index(op.f('ix_internal_chat_messages_id'), table_name='internal_chat_messages')
    op.drop_table('internal_chat_messages')
    op.drop_index(op.f('ix_intents_id'), table_name='intents')
    op.drop_table('intents')
    op.drop_index(op.f('ix_conversation_sessions_id'), table_name='conversation_sessions')
    op.drop_index(op.f('ix_conversation_sessions_conversation_id'), table_name='conversation_sessions')
    op.drop_table('conversation_sessions')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_channel_memberships_id'), table_name='channel_memberships')
    op.drop_table('channel_memberships')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_segment_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_name'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_company_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_campaign_type'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_workflows_name'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_widget_settings_id'), table_name='widget_settings')
    op.drop_table('widget_settings')
    op.drop_index(op.f('ix_webhooks_name'), table_name='webhooks')
    op.drop_index(op.f('ix_webhooks_id'), table_name='webhooks')
    op.drop_table('webhooks')
    op.drop_index(op.f('ix_voice_profiles_provider_voice_id'), table_name='voice_profiles')
    op.drop_index(op.f('ix_voice_profiles_name'), table_name='voice_profiles')
    op.drop_index(op.f('ix_voice_profiles_id'), table_name='voice_profiles')
    op.drop_table('voice_profiles')
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_templates_template_type'), table_name='templates')
    op.drop_index(op.f('ix_templates_id'), table_name='templates')
    op.drop_index(op.f('ix_templates_company_id'), table_name='templates')
    op.drop_table('templates')
    op.drop_index(op.f('ix_team_memberships_id'), table_name='team_memberships')
    op.drop_table('team_memberships')
    op.drop_index(op.f('ix_segments_name'), table_name='segments')
    op.drop_index(op.f('ix_segments_id'), table_name='segments')
    op.drop_index(op.f('ix_segments_company_id'), table_name='segments')
    op.drop_table('segments')
    op.drop_index(op.f('ix_optimization_suggestions_id'), table_name='optimization_suggestions')
    op.drop_table('optimization_suggestions')
    op.drop_index(op.f('ix_message_templates_shortcut'), table_name='message_templates')
    op.drop_index(op.f('ix_message_templates_scope'), table_name='message_templates')
    op.drop_index(op.f('ix_message_templates_id'), table_name='message_templates')
    op.drop_index(op.f('ix_message_templates_created_by_user_id'), table_name='message_templates')
    op.drop_index(op.f('ix_message_templates_company_id'), table_name='message_templates')
    op.drop_table('message_templates')
    op.drop_index(op.f('ix_memories_session_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_key'), table_name='memories')
    op.drop_index(op.f('ix_memories_id'), table_name='memories')
    op.drop_table('memories')
    op.drop_index(op.f('ix_conversation_tags_tag'), table_name='conversation_tags')
    op.drop_index(op.f('ix_conversation_tags_id'), table_name='conversation_tags')
    op.drop_index(op.f('ix_conversation_tags_conversation_id'), table_name='conversation_tags')
    op.drop_table('conversation_tags')
    op.drop_index(op.f('ix_chat_channels_id'), table_name='chat_channels')
    op.drop_table('chat_channels')
    op.drop_table('ai_tool_favorites')
    op.drop_table('agent_tools')
    op.drop_table('agent_knowledge_bases')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_table('contact_tags')
    op.drop_index(op.f('ix_ai_tool_questions_id'), table_name='ai_tool_questions')
    op.drop_table('ai_tool_questions')
    op.drop_index(op.f('ix_agents_name'), table_name='agents')
    op.drop_index(op.f('ix_agents_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_tools_name'), table_name='tools')
    op.drop_index(op.f('ix_tools_id'), table_name='tools')
    op.drop_table('tools')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_index(op.f('ix_tags_company_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_processing_templates_name'), table_name='processing_templates')
    op.drop_index(op.f('ix_processing_templates_id'), table_name='processing_templates')
    op.drop_table('processing_templates')
    op.drop_index(op.f('ix_notification_settings_id'), table_name='notification_settings')
    op.drop_table('notification_settings')
    op.drop_index(op.f('ix_knowledge_bases_name'), table_name='knowledge_bases')
    op.drop_index(op.f('ix_knowledge_bases_id'), table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    op.drop_index(op.f('ix_integrations_type'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_id'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_entities_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_credentials_service'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_name'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_id'), table_name='credentials')
    op.drop_table('credentials')
    op.drop_index(op.f('ix_contacts_name'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_lifecycle_stage'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_lead_source'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_company_settings_id'), table_name='company_settings')
    op.drop_table('company_settings')
    op.drop_index(op.f('ix_api_keys_key'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_ai_tools_name'), table_name='ai_tools')
    op.drop_index(op.f('ix_ai_tools_id'), table_name='ai_tools')
    op.drop_table('ai_tools')
    op.drop_index(op.f('ix_temporary_documents_id'), table_name='temporary_documents')
    op.drop_index(op.f('ix_temporary_documents_document_id'), table_name='temporary_documents')
    op.drop_table('temporary_documents')
    op.drop_index(op.f('ix_subscription_plans_name'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_id'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_published_widget_settings_publish_id'), table_name='published_widget_settings')
    op.drop_index(op.f('ix_published_widget_settings_id'), table_name='published_widget_settings')
    op.drop_table('published_widget_settings')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_ai_tool_categories_name'), table_name='ai_tool_categories')
    op.drop_index(op.f('ix_ai_tool_categories_id'), table_name='ai_tool_categories')
    op.drop_table('ai_tool_categories')
    op.drop_index(op.f('ix_ai_images_id'), table_name='ai_images')
    op.drop_table('ai_images')
    # ### end Alembic commands ###
