"""add_parent_message_id_for_threads

Revision ID: 7539dc0ae132
Revises: a49b7c540470
Create Date: 2025-11-12 21:53:36.689762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7539dc0ae132'
down_revision: Union[str, Sequence[str], None] = 'a49b7c540470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('internal_chat_messages', sa.Column('parent_message_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'internal_chat_messages', 'internal_chat_messages', ['parent_message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'internal_chat_messages', type_='foreignkey')
    op.drop_column('internal_chat_messages', 'parent_message_id')
    # ### end Alembic commands ###
