"""add_email_signature_to_company_settings

Revision ID: 784d7abf9112
Revises: a673599be1cd
Create Date: 2026-03-14 01:16:47.578627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '784d7abf9112'
down_revision: Union[str, Sequence[str], None] = 'a673599be1cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_settings', sa.Column('email_signature', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_settings', 'email_signature')
    # ### end Alembic commands ###
