"""add_workflow_templates_table

Revision ID: 93c70d915e2c
Revises: 4ba156244682
Create Date: 2025-12-18 21:10:36.994365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93c70d915e2c'
down_revision: Union[str, Sequence[str], None] = '4ba156244682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('visual_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trigger_phrases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('intent_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_templates_category'), 'workflow_templates', ['category'], unique=False)
    op.create_index(op.f('ix_workflow_templates_company_id'), 'workflow_templates', ['company_id'], unique=False)
    op.create_index(op.f('ix_workflow_templates_id'), 'workflow_templates', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_templates_is_system'), 'workflow_templates', ['is_system'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_templates_is_system'), table_name='workflow_templates')
    op.drop_index(op.f('ix_workflow_templates_id'), table_name='workflow_templates')
    op.drop_index(op.f('ix_workflow_templates_company_id'), table_name='workflow_templates')
    op.drop_index(op.f('ix_workflow_templates_category'), table_name='workflow_templates')
    op.drop_table('workflow_templates')
    # ### end Alembic commands ###
