"""add_message_mentions_table

Revision ID: 9e26dc76c0d8
Revises: 6992d42b3279
Create Date: 2025-11-12 22:03:18.005304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e26dc76c0d8'
down_revision: Union[str, Sequence[str], None] = '6992d42b3279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_mentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('mentioned_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['mentioned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['internal_chat_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_mentions_id'), 'message_mentions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_mentions_id'), table_name='message_mentions')
    op.drop_table('message_mentions')
    # ### end Alembic commands ###
