"""Add CRM system with leads campaigns and enhanced contacts

Revision ID: 9febb8f73f38
Revises: 14adb0b61ef9
Create Date: 2025-11-23 12:24:08.729976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9febb8f73f38'
down_revision: Union[str, Sequence[str], None] = '14adb0b61ef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop existing CRM tables if they exist (to handle reruns)
    op.execute("DROP TABLE IF EXISTS lead_scores CASCADE")
    op.execute("DROP TABLE IF EXISTS campaign_activities CASCADE")
    op.execute("DROP TABLE IF EXISTS campaign_contacts CASCADE")
    op.execute("DROP TABLE IF EXISTS campaign_messages CASCADE")
    op.execute("DROP TABLE IF EXISTS leads CASCADE")
    op.execute("DROP TABLE IF EXISTS campaigns CASCADE")

    # Drop existing enum types if they exist (to handle reruns)
    op.execute("DROP TYPE IF EXISTS campaigntype CASCADE")
    op.execute("DROP TYPE IF EXISTS campaignstatus CASCADE")
    op.execute("DROP TYPE IF EXISTS goaltype CASCADE")
    op.execute("DROP TYPE IF EXISTS messagetype CASCADE")
    op.execute("DROP TYPE IF EXISTS delayunit CASCADE")
    op.execute("DROP TYPE IF EXISTS enrollmentstatus CASCADE")
    op.execute("DROP TYPE IF EXISTS activitytype CASCADE")
    op.execute("DROP TYPE IF EXISTS leadstage CASCADE")
    op.execute("DROP TYPE IF EXISTS qualificationstatus CASCADE")
    op.execute("DROP TYPE IF EXISTS scoretype CASCADE")
    op.execute("DROP TYPE IF EXISTS lifecyclestage CASCADE")
    op.execute("DROP TYPE IF EXISTS optinstatus CASCADE")

    # Explicitly create enum types needed for contacts table before table modifications
    op.execute("CREATE TYPE lifecyclestage AS ENUM ('SUBSCRIBER', 'LEAD', 'MQL', 'SQL', 'OPPORTUNITY', 'CUSTOMER', 'EVANGELIST', 'OTHER')")
    op.execute("CREATE TYPE optinstatus AS ENUM ('OPTED_IN', 'OPTED_OUT', 'PENDING', 'UNKNOWN')")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('campaign_type', sa.Enum('EMAIL', 'SMS', 'WHATSAPP', 'VOICE', 'MULTI_CHANNEL', name='campaigntype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'ACTIVE', 'PAUSED', 'COMPLETED', 'ARCHIVED', name='campaignstatus'), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('scheduled_send_time', sa.DateTime(), nullable=True),
    sa.Column('target_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('goal_type', sa.Enum('LEAD_GENERATION', 'NURTURE', 'CONVERSION', 'ENGAGEMENT', 'RETENTION', 'REACTIVATION', name='goaltype'), nullable=True),
    sa.Column('goal_value', sa.Integer(), nullable=True),
    sa.Column('budget', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('actual_cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('twilio_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_contacts', sa.Integer(), nullable=False),
    sa.Column('contacts_reached', sa.Integer(), nullable=False),
    sa.Column('contacts_engaged', sa.Integer(), nullable=False),
    sa.Column('contacts_converted', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_campaign_type'), 'campaigns', ['campaign_type'], unique=False)
    op.create_index(op.f('ix_campaigns_company_id'), 'campaigns', ['company_id'], unique=False)
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_index(op.f('ix_campaigns_name'), 'campaigns', ['name'], unique=False)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_table('campaign_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('message_type', sa.Enum('EMAIL', 'SMS', 'WHATSAPP', 'VOICE', 'AI_CONVERSATION', name='messagetype'), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('html_body', sa.Text(), nullable=True),
    sa.Column('voice_script', sa.Text(), nullable=True),
    sa.Column('tts_voice_id', sa.String(), nullable=True),
    sa.Column('voice_agent_id', sa.Integer(), nullable=True),
    sa.Column('twilio_phone_number', sa.String(), nullable=True),
    sa.Column('call_flow_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('whatsapp_template_name', sa.String(), nullable=True),
    sa.Column('whatsapp_template_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('delay_amount', sa.Integer(), nullable=False),
    sa.Column('delay_unit', sa.Enum('MINUTES', 'HOURS', 'DAYS', 'WEEKS', name='delayunit'), nullable=False),
    sa.Column('send_time_window_start', sa.String(), nullable=True),
    sa.Column('send_time_window_end', sa.String(), nullable=True),
    sa.Column('send_on_weekdays_only', sa.Boolean(), nullable=False),
    sa.Column('is_ab_test', sa.Boolean(), nullable=False),
    sa.Column('ab_variant', sa.String(), nullable=True),
    sa.Column('ab_split_percentage', sa.Integer(), nullable=True),
    sa.Column('personalization_tokens', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cta_text', sa.String(), nullable=True),
    sa.Column('cta_url', sa.String(), nullable=True),
    sa.Column('track_clicks', sa.Boolean(), nullable=False),
    sa.Column('send_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['voice_agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_messages_campaign_id'), 'campaign_messages', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_messages_id'), 'campaign_messages', ['id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.Enum('LEAD', 'MQL', 'SQL', 'OPPORTUNITY', 'CUSTOMER', 'LOST', name='leadstage'), nullable=False),
    sa.Column('stage_changed_at', sa.DateTime(), nullable=False),
    sa.Column('previous_stage', sa.Enum('LEAD', 'MQL', 'SQL', 'OPPORTUNITY', 'CUSTOMER', 'LOST', name='leadstage'), nullable=True),
    sa.Column('qualification_status', sa.Enum('UNQUALIFIED', 'IN_PROGRESS', 'QUALIFIED', 'DISQUALIFIED', name='qualificationstatus'), nullable=False),
    sa.Column('qualification_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('last_scored_at', sa.DateTime(), nullable=True),
    sa.Column('deal_value', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('expected_close_date', sa.DateTime(), nullable=True),
    sa.Column('actual_close_date', sa.DateTime(), nullable=True),
    sa.Column('won_reason', sa.String(), nullable=True),
    sa.Column('lost_reason', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_assignee_id'), 'leads', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_leads_campaign_id'), 'leads', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_leads_company_id'), 'leads', ['company_id'], unique=False)
    op.create_index(op.f('ix_leads_contact_id'), 'leads', ['contact_id'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_score'), 'leads', ['score'], unique=False)
    op.create_index(op.f('ix_leads_source'), 'leads', ['source'], unique=False)
    op.create_index(op.f('ix_leads_stage'), 'leads', ['stage'], unique=False)
    op.create_table('campaign_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.Enum('EMAIL_SENT', 'EMAIL_DELIVERED', 'EMAIL_OPENED', 'EMAIL_CLICKED', 'EMAIL_REPLIED', 'EMAIL_BOUNCED', 'EMAIL_UNSUBSCRIBED', 'SMS_SENT', 'SMS_DELIVERED', 'SMS_REPLIED', 'SMS_FAILED', 'WHATSAPP_SENT', 'WHATSAPP_DELIVERED', 'WHATSAPP_READ', 'WHATSAPP_REPLIED', 'CALL_INITIATED', 'CALL_RINGING', 'CALL_ANSWERED', 'CALL_COMPLETED', 'CALL_FAILED', 'CALL_BUSY', 'CALL_NO_ANSWER', 'VOICEMAIL_DETECTED', 'VOICEMAIL_LEFT', 'CONVERSATION_STARTED', 'CONVERSATION_REPLIED', 'CONVERSATION_ENDED', 'FORM_SUBMITTED', 'MEETING_BOOKED', 'LEAD_QUALIFIED', 'OPPORTUNITY_CREATED', 'DEAL_WON', 'DEAL_LOST', 'LINK_CLICKED', 'CONTENT_VIEWED', 'DOCUMENT_DOWNLOADED', 'OPTED_OUT', 'ERROR', name='activitytype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('activity_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('revenue_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['campaign_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_activities_activity_type'), 'campaign_activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_campaign_activities_campaign_id'), 'campaign_activities', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_activities_contact_id'), 'campaign_activities', ['contact_id'], unique=False)
    op.create_index(op.f('ix_campaign_activities_external_id'), 'campaign_activities', ['external_id'], unique=False)
    op.create_index(op.f('ix_campaign_activities_id'), 'campaign_activities', ['id'], unique=False)
    op.create_index(op.f('ix_campaign_activities_lead_id'), 'campaign_activities', ['lead_id'], unique=False)
    op.create_index(op.f('ix_campaign_activities_message_id'), 'campaign_activities', ['message_id'], unique=False)
    op.create_index(op.f('ix_campaign_activities_session_id'), 'campaign_activities', ['session_id'], unique=False)
    op.create_index(op.f('ix_campaign_activities_timestamp'), 'campaign_activities', ['timestamp'], unique=False)
    op.create_table('campaign_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(), nullable=False),
    sa.Column('enrolled_by_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'COMPLETED', 'OPTED_OUT', 'BOUNCED', 'FAILED', 'PAUSED', name='enrollmentstatus'), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('current_message_id', sa.Integer(), nullable=True),
    sa.Column('next_scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('last_interaction_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('opted_out_at', sa.DateTime(), nullable=True),
    sa.Column('opt_out_reason', sa.String(), nullable=True),
    sa.Column('opens', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('replies', sa.Integer(), nullable=False),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('calls_initiated', sa.Integer(), nullable=False),
    sa.Column('calls_completed', sa.Integer(), nullable=False),
    sa.Column('total_call_duration', sa.Integer(), nullable=False),
    sa.Column('voicemails_left', sa.Integer(), nullable=False),
    sa.Column('enrollment_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['current_message_id'], ['campaign_messages.id'], ),
    sa.ForeignKeyConstraint(['enrolled_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'contact_id', name='uq_campaign_contact')
    )
    op.create_index(op.f('ix_campaign_contacts_campaign_id'), 'campaign_contacts', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_contacts_contact_id'), 'campaign_contacts', ['contact_id'], unique=False)
    op.create_index(op.f('ix_campaign_contacts_id'), 'campaign_contacts', ['id'], unique=False)
    op.create_index(op.f('ix_campaign_contacts_lead_id'), 'campaign_contacts', ['lead_id'], unique=False)
    op.create_index(op.f('ix_campaign_contacts_status'), 'campaign_contacts', ['status'], unique=False)
    op.create_table('lead_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('score_type', sa.Enum('AI_INTENT', 'ENGAGEMENT', 'DEMOGRAPHIC', 'BEHAVIORAL', 'WORKFLOW', 'MANUAL', 'COMBINED', name='scoretype'), nullable=False),
    sa.Column('score_value', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('score_reason', sa.Text(), nullable=True),
    sa.Column('score_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('intent_matches', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scored_by_user_id', sa.Integer(), nullable=True),
    sa.Column('scored_by_agent_id', sa.Integer(), nullable=True),
    sa.Column('conversation_session_id', sa.String(), nullable=True),
    sa.Column('scored_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('score_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['scored_by_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['scored_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_scores_company_id'), 'lead_scores', ['company_id'], unique=False)
    op.create_index(op.f('ix_lead_scores_id'), 'lead_scores', ['id'], unique=False)
    op.create_index(op.f('ix_lead_scores_lead_id'), 'lead_scores', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_scores_score_type'), 'lead_scores', ['score_type'], unique=False)
    op.create_index(op.f('ix_lead_scores_scored_at'), 'lead_scores', ['scored_at'], unique=False)
    op.add_column('contacts', sa.Column('lead_source', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('lifecycle_stage', sa.Enum('SUBSCRIBER', 'LEAD', 'MQL', 'SQL', 'OPPORTUNITY', 'CUSTOMER', 'EVANGELIST', 'OTHER', name='lifecyclestage'), nullable=True))
    op.add_column('contacts', sa.Column('do_not_contact', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('contacts', sa.Column('opt_in_status', sa.Enum('OPTED_IN', 'OPTED_OUT', 'PENDING', 'UNKNOWN', name='optinstatus'), nullable=False, server_default='UNKNOWN'))
    op.add_column('contacts', sa.Column('opt_in_date', sa.DateTime(), nullable=True))
    op.add_column('contacts', sa.Column('opt_out_date', sa.DateTime(), nullable=True))
    op.add_column('contacts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('contacts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('contacts', sa.Column('last_contacted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_contacts_lead_source'), 'contacts', ['lead_source'], unique=False)
    op.create_index(op.f('ix_contacts_lifecycle_stage'), 'contacts', ['lifecycle_stage'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contacts_lifecycle_stage'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_lead_source'), table_name='contacts')
    op.drop_column('contacts', 'last_contacted_at')
    op.drop_column('contacts', 'updated_at')
    op.drop_column('contacts', 'created_at')
    op.drop_column('contacts', 'opt_out_date')
    op.drop_column('contacts', 'opt_in_date')
    op.drop_column('contacts', 'opt_in_status')
    op.drop_column('contacts', 'do_not_contact')
    op.drop_column('contacts', 'lifecycle_stage')
    op.drop_column('contacts', 'lead_source')
    op.drop_index(op.f('ix_lead_scores_scored_at'), table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_score_type'), table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_lead_id'), table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_id'), table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_company_id'), table_name='lead_scores')
    op.drop_table('lead_scores')
    op.drop_index(op.f('ix_campaign_contacts_status'), table_name='campaign_contacts')
    op.drop_index(op.f('ix_campaign_contacts_lead_id'), table_name='campaign_contacts')
    op.drop_index(op.f('ix_campaign_contacts_id'), table_name='campaign_contacts')
    op.drop_index(op.f('ix_campaign_contacts_contact_id'), table_name='campaign_contacts')
    op.drop_index(op.f('ix_campaign_contacts_campaign_id'), table_name='campaign_contacts')
    op.drop_table('campaign_contacts')
    op.drop_index(op.f('ix_campaign_activities_timestamp'), table_name='campaign_activities')
    op.drop_index(op.f('ix_campaign_activities_session_id'), table_name='campaign_activities')
    op.drop_index(op.f('ix_campaign_activities_message_id'), table_name='campaign_activities')
    op.drop_index(op.f('ix_campaign_activities_lead_id'), table_name='campaign_activities')
    op.drop_index(op.f('ix_campaign_activities_id'), table_name='campaign_activities')
    op.drop_index(op.f('ix_campaign_activities_external_id'), table_name='campaign_activities')
    op.drop_index(op.f('ix_campaign_activities_contact_id'), table_name='campaign_activities')
    op.drop_index(op.f('ix_campaign_activities_campaign_id'), table_name='campaign_activities')
    op.drop_index(op.f('ix_campaign_activities_activity_type'), table_name='campaign_activities')
    op.drop_table('campaign_activities')
    op.drop_index(op.f('ix_leads_stage'), table_name='leads')
    op.drop_index(op.f('ix_leads_source'), table_name='leads')
    op.drop_index(op.f('ix_leads_score'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_contact_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_company_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_campaign_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_assignee_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_campaign_messages_id'), table_name='campaign_messages')
    op.drop_index(op.f('ix_campaign_messages_campaign_id'), table_name='campaign_messages')
    op.drop_table('campaign_messages')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_name'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_company_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_campaign_type'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
