"""Replace Stripe with Razorpay fields

Revision ID: a673599be1cd
Revises: i8j9k0l1m2n3
Create Date: 2026-01-28 00:59:21.372328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a673599be1cd'
down_revision: Union[str, Sequence[str], None] = 'i8j9k0l1m2n3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_integrations_api_key_id'), table_name='api_integrations')
    op.drop_constraint(op.f('api_integrations_company_id_fkey'), 'api_integrations', type_='foreignkey')
    op.drop_constraint(op.f('api_integrations_api_key_id_fkey'), 'api_integrations', type_='foreignkey')
    op.drop_constraint(op.f('api_integrations_default_workflow_id_fkey'), 'api_integrations', type_='foreignkey')
    op.drop_constraint(op.f('api_integrations_default_agent_id_fkey'), 'api_integrations', type_='foreignkey')
    op.create_foreign_key(None, 'api_integrations', 'agents', ['default_agent_id'], ['id'])
    op.create_foreign_key(None, 'api_integrations', 'api_keys', ['api_key_id'], ['id'])
    op.create_foreign_key(None, 'api_integrations', 'workflows', ['default_workflow_id'], ['id'])
    op.create_foreign_key(None, 'api_integrations', 'companies', ['company_id'], ['id'])
    op.add_column('company_subscriptions', sa.Column('razorpay_customer_id', sa.String(), nullable=True))
    op.add_column('company_subscriptions', sa.Column('razorpay_subscription_id', sa.String(), nullable=True))
    op.drop_index(op.f('ix_company_subscriptions_company_id'), table_name='company_subscriptions')
    op.drop_index(op.f('ix_company_subscriptions_stripe_customer_id'), table_name='company_subscriptions')
    op.drop_index(op.f('ix_company_subscriptions_stripe_subscription_id'), table_name='company_subscriptions')
    op.create_index(op.f('ix_company_subscriptions_razorpay_customer_id'), 'company_subscriptions', ['razorpay_customer_id'], unique=False)
    op.create_index(op.f('ix_company_subscriptions_razorpay_subscription_id'), 'company_subscriptions', ['razorpay_subscription_id'], unique=False)
    op.create_unique_constraint(None, 'company_subscriptions', ['company_id'])
    op.drop_constraint(op.f('company_subscriptions_company_id_fkey'), 'company_subscriptions', type_='foreignkey')
    op.drop_constraint(op.f('company_subscriptions_subscription_plan_id_fkey'), 'company_subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'company_subscriptions', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'company_subscriptions', 'subscription_plans', ['subscription_plan_id'], ['id'])
    op.drop_column('company_subscriptions', 'stripe_subscription_id')
    op.drop_column('company_subscriptions', 'stripe_customer_id')
    op.alter_column('content_api_tokens', 'can_read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('content_api_tokens', 'can_search',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('content_api_tokens', 'rate_limit',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('100'))
    op.alter_column('content_api_tokens', 'request_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('content_api_tokens', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_constraint(op.f('uq_content_api_tokens_token'), 'content_api_tokens', type_='unique')
    op.drop_constraint(op.f('content_api_tokens_knowledge_base_id_fkey'), 'content_api_tokens', type_='foreignkey')
    op.drop_constraint(op.f('content_api_tokens_company_id_fkey'), 'content_api_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'content_api_tokens', 'knowledge_bases', ['knowledge_base_id'], ['id'])
    op.create_foreign_key(None, 'content_api_tokens', 'companies', ['company_id'], ['id'])
    op.alter_column('content_categories', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(op.f('uq_content_categories_company_kb_slug'), 'content_categories', type_='unique')
    op.drop_constraint(op.f('content_categories_parent_id_fkey'), 'content_categories', type_='foreignkey')
    op.drop_constraint(op.f('content_categories_knowledge_base_id_fkey'), 'content_categories', type_='foreignkey')
    op.drop_constraint(op.f('content_categories_company_id_fkey'), 'content_categories', type_='foreignkey')
    op.create_foreign_key(None, 'content_categories', 'content_categories', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'content_categories', 'knowledge_bases', ['knowledge_base_id'], ['id'])
    op.create_foreign_key(None, 'content_categories', 'companies', ['company_id'], ['id'])
    op.drop_constraint(op.f('content_copies_copied_by_user_id_fkey'), 'content_copies', type_='foreignkey')
    op.drop_constraint(op.f('content_copies_original_company_id_fkey'), 'content_copies', type_='foreignkey')
    op.drop_constraint(op.f('content_copies_copied_by_company_id_fkey'), 'content_copies', type_='foreignkey')
    op.drop_constraint(op.f('content_copies_copied_item_id_fkey'), 'content_copies', type_='foreignkey')
    op.drop_constraint(op.f('content_copies_original_item_id_fkey'), 'content_copies', type_='foreignkey')
    op.create_foreign_key(None, 'content_copies', 'content_items', ['copied_item_id'], ['id'])
    op.create_foreign_key(None, 'content_copies', 'content_items', ['original_item_id'], ['id'])
    op.create_foreign_key(None, 'content_copies', 'companies', ['copied_by_company_id'], ['id'])
    op.create_foreign_key(None, 'content_copies', 'companies', ['original_company_id'], ['id'])
    op.create_foreign_key(None, 'content_copies', 'users', ['copied_by_user_id'], ['id'])
    op.alter_column('content_exports', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_constraint(op.f('content_exports_company_id_fkey'), 'content_exports', type_='foreignkey')
    op.drop_constraint(op.f('content_exports_requested_by_fkey'), 'content_exports', type_='foreignkey')
    op.drop_constraint(op.f('content_exports_knowledge_base_id_fkey'), 'content_exports', type_='foreignkey')
    op.create_foreign_key(None, 'content_exports', 'knowledge_bases', ['knowledge_base_id'], ['id'])
    op.create_foreign_key(None, 'content_exports', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'content_exports', 'users', ['requested_by'], ['id'])
    op.alter_column('content_items', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('content_items', 'visibility',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'private'::character varying"))
    op.alter_column('content_items', 'is_featured',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('content_items', 'download_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('content_items', 'version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_content_items_data'), table_name='content_items', postgresql_using='gin')
    op.drop_constraint(op.f('content_items_company_id_fkey'), 'content_items', type_='foreignkey')
    op.drop_constraint(op.f('content_items_created_by_fkey'), 'content_items', type_='foreignkey')
    op.drop_constraint(op.f('content_items_knowledge_base_id_fkey'), 'content_items', type_='foreignkey')
    op.drop_constraint(op.f('content_items_updated_by_fkey'), 'content_items', type_='foreignkey')
    op.drop_constraint(op.f('content_items_content_type_id_fkey'), 'content_items', type_='foreignkey')
    op.create_foreign_key(None, 'content_items', 'knowledge_bases', ['knowledge_base_id'], ['id'])
    op.create_foreign_key(None, 'content_items', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'content_items', 'content_types', ['content_type_id'], ['id'])
    op.create_foreign_key(None, 'content_items', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'content_items', 'users', ['created_by'], ['id'])
    op.alter_column('content_media', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(op.f('content_media_uploaded_by_fkey'), 'content_media', type_='foreignkey')
    op.drop_constraint(op.f('content_media_company_id_fkey'), 'content_media', type_='foreignkey')
    op.create_foreign_key(None, 'content_media', 'users', ['uploaded_by'], ['id'])
    op.create_foreign_key(None, 'content_media', 'companies', ['company_id'], ['id'])
    op.alter_column('content_tags', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(op.f('uq_content_tags_company_slug'), 'content_tags', type_='unique')
    op.drop_constraint(op.f('content_tags_company_id_fkey'), 'content_tags', type_='foreignkey')
    op.create_foreign_key(None, 'content_tags', 'companies', ['company_id'], ['id'])
    op.alter_column('content_types', 'allow_public_publish',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_constraint(op.f('uq_content_types_company_slug'), 'content_types', type_='unique')
    op.drop_constraint(op.f('content_types_company_id_fkey'), 'content_types', type_='foreignkey')
    op.drop_constraint(op.f('content_types_knowledge_base_id_fkey'), 'content_types', type_='foreignkey')
    op.create_foreign_key(None, 'content_types', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'content_types', 'knowledge_bases', ['knowledge_base_id'], ['id'])
    op.add_column('subscription_plans', sa.Column('razorpay_plan_id', sa.String(), nullable=True))
    op.drop_index(op.f('ix_subscription_plans_stripe_price_id'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_stripe_product_id'), table_name='subscription_plans')
    op.create_index(op.f('ix_subscription_plans_razorpay_plan_id'), 'subscription_plans', ['razorpay_plan_id'], unique=False)
    op.drop_column('subscription_plans', 'stripe_product_id')
    op.drop_column('subscription_plans', 'stripe_price_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_plans', sa.Column('stripe_price_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('subscription_plans', sa.Column('stripe_product_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_subscription_plans_razorpay_plan_id'), table_name='subscription_plans')
    op.create_index(op.f('ix_subscription_plans_stripe_product_id'), 'subscription_plans', ['stripe_product_id'], unique=False)
    op.create_index(op.f('ix_subscription_plans_stripe_price_id'), 'subscription_plans', ['stripe_price_id'], unique=False)
    op.drop_column('subscription_plans', 'razorpay_plan_id')
    op.drop_constraint(None, 'content_types', type_='foreignkey')
    op.drop_constraint(None, 'content_types', type_='foreignkey')
    op.create_foreign_key(op.f('content_types_knowledge_base_id_fkey'), 'content_types', 'knowledge_bases', ['knowledge_base_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('content_types_company_id_fkey'), 'content_types', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_content_types_company_slug'), 'content_types', ['company_id', 'slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('content_types', 'allow_public_publish',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint(None, 'content_tags', type_='foreignkey')
    op.create_foreign_key(op.f('content_tags_company_id_fkey'), 'content_tags', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_content_tags_company_slug'), 'content_tags', ['company_id', 'slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('content_tags', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'content_media', type_='foreignkey')
    op.drop_constraint(None, 'content_media', type_='foreignkey')
    op.create_foreign_key(op.f('content_media_company_id_fkey'), 'content_media', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('content_media_uploaded_by_fkey'), 'content_media', 'users', ['uploaded_by'], ['id'], ondelete='SET NULL')
    op.alter_column('content_media', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'content_items', type_='foreignkey')
    op.drop_constraint(None, 'content_items', type_='foreignkey')
    op.drop_constraint(None, 'content_items', type_='foreignkey')
    op.drop_constraint(None, 'content_items', type_='foreignkey')
    op.drop_constraint(None, 'content_items', type_='foreignkey')
    op.create_foreign_key(op.f('content_items_content_type_id_fkey'), 'content_items', 'content_types', ['content_type_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('content_items_updated_by_fkey'), 'content_items', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('content_items_knowledge_base_id_fkey'), 'content_items', 'knowledge_bases', ['knowledge_base_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('content_items_created_by_fkey'), 'content_items', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('content_items_company_id_fkey'), 'content_items', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_content_items_data'), 'content_items', ['data'], unique=False, postgresql_using='gin')
    op.alter_column('content_items', 'version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('content_items', 'download_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('content_items', 'is_featured',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('content_items', 'visibility',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'private'::character varying"))
    op.alter_column('content_items', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.drop_constraint(None, 'content_exports', type_='foreignkey')
    op.drop_constraint(None, 'content_exports', type_='foreignkey')
    op.drop_constraint(None, 'content_exports', type_='foreignkey')
    op.create_foreign_key(op.f('content_exports_knowledge_base_id_fkey'), 'content_exports', 'knowledge_bases', ['knowledge_base_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('content_exports_requested_by_fkey'), 'content_exports', 'users', ['requested_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('content_exports_company_id_fkey'), 'content_exports', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.alter_column('content_exports', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_constraint(None, 'content_copies', type_='foreignkey')
    op.drop_constraint(None, 'content_copies', type_='foreignkey')
    op.drop_constraint(None, 'content_copies', type_='foreignkey')
    op.drop_constraint(None, 'content_copies', type_='foreignkey')
    op.drop_constraint(None, 'content_copies', type_='foreignkey')
    op.create_foreign_key(op.f('content_copies_original_item_id_fkey'), 'content_copies', 'content_items', ['original_item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('content_copies_copied_item_id_fkey'), 'content_copies', 'content_items', ['copied_item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('content_copies_copied_by_company_id_fkey'), 'content_copies', 'companies', ['copied_by_company_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('content_copies_original_company_id_fkey'), 'content_copies', 'companies', ['original_company_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('content_copies_copied_by_user_id_fkey'), 'content_copies', 'users', ['copied_by_user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'content_categories', type_='foreignkey')
    op.drop_constraint(None, 'content_categories', type_='foreignkey')
    op.drop_constraint(None, 'content_categories', type_='foreignkey')
    op.create_foreign_key(op.f('content_categories_company_id_fkey'), 'content_categories', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('content_categories_knowledge_base_id_fkey'), 'content_categories', 'knowledge_bases', ['knowledge_base_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('content_categories_parent_id_fkey'), 'content_categories', 'content_categories', ['parent_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(op.f('uq_content_categories_company_kb_slug'), 'content_categories', ['company_id', 'knowledge_base_id', 'slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('content_categories', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'content_api_tokens', type_='foreignkey')
    op.drop_constraint(None, 'content_api_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('content_api_tokens_company_id_fkey'), 'content_api_tokens', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('content_api_tokens_knowledge_base_id_fkey'), 'content_api_tokens', 'knowledge_bases', ['knowledge_base_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(op.f('uq_content_api_tokens_token'), 'content_api_tokens', ['token'], postgresql_nulls_not_distinct=False)
    op.alter_column('content_api_tokens', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('content_api_tokens', 'request_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('content_api_tokens', 'rate_limit',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('100'))
    op.alter_column('content_api_tokens', 'can_search',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('content_api_tokens', 'can_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.add_column('company_subscriptions', sa.Column('stripe_customer_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('company_subscriptions', sa.Column('stripe_subscription_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'company_subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'company_subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('company_subscriptions_subscription_plan_id_fkey'), 'company_subscriptions', 'subscription_plans', ['subscription_plan_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('company_subscriptions_company_id_fkey'), 'company_subscriptions', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'company_subscriptions', type_='unique')
    op.drop_index(op.f('ix_company_subscriptions_razorpay_subscription_id'), table_name='company_subscriptions')
    op.drop_index(op.f('ix_company_subscriptions_razorpay_customer_id'), table_name='company_subscriptions')
    op.create_index(op.f('ix_company_subscriptions_stripe_subscription_id'), 'company_subscriptions', ['stripe_subscription_id'], unique=False)
    op.create_index(op.f('ix_company_subscriptions_stripe_customer_id'), 'company_subscriptions', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_company_subscriptions_company_id'), 'company_subscriptions', ['company_id'], unique=True)
    op.drop_column('company_subscriptions', 'razorpay_subscription_id')
    op.drop_column('company_subscriptions', 'razorpay_customer_id')
    op.drop_constraint(None, 'api_integrations', type_='foreignkey')
    op.drop_constraint(None, 'api_integrations', type_='foreignkey')
    op.drop_constraint(None, 'api_integrations', type_='foreignkey')
    op.drop_constraint(None, 'api_integrations', type_='foreignkey')
    op.create_foreign_key(op.f('api_integrations_default_agent_id_fkey'), 'api_integrations', 'agents', ['default_agent_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('api_integrations_default_workflow_id_fkey'), 'api_integrations', 'workflows', ['default_workflow_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('api_integrations_api_key_id_fkey'), 'api_integrations', 'api_keys', ['api_key_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('api_integrations_company_id_fkey'), 'api_integrations', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_api_integrations_api_key_id'), 'api_integrations', ['api_key_id'], unique=True)
    # ### end Alembic commands ###
