"""add_tags_and_segments_for_campaign_targeting

Revision ID: bda61ca8e2c3
Revises: 9febb8f73f38
Create Date: 2025-11-29 14:10:25.214801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bda61ca8e2c3'
down_revision: Union[str, Sequence[str], None] = '9febb8f73f38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('segment_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_campaigns_segment_id'), 'campaigns', ['segment_id'], unique=False)
    op.create_foreign_key(None, 'campaigns', 'segments', ['segment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_index(op.f('ix_campaigns_segment_id'), table_name='campaigns')
    op.drop_column('campaigns', 'segment_id')
    # ### end Alembic commands ###
