"""add_ticket_sprints

Revision ID: ceaff61e3fda
Revises: eeab9d60d728
Create Date: 2026-05-08 23:19:03.332424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceaff61e3fda'
down_revision: Union[str, Sequence[str], None] = 'eeab9d60d728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_sprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('FUTURE', 'ACTIVE', 'COMPLETED', name='sprintstatus'), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['ticket_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_sprints_company_id'), 'ticket_sprints', ['company_id'], unique=False)
    op.create_index(op.f('ix_ticket_sprints_id'), 'ticket_sprints', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_sprints_project_id'), 'ticket_sprints', ['project_id'], unique=False)
    op.create_index(op.f('ix_ticket_sprints_status'), 'ticket_sprints', ['status'], unique=False)
    op.add_column('tickets', sa.Column('sprint_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tickets_sprint_id'), 'tickets', ['sprint_id'], unique=False)
    op.create_foreign_key(None, 'tickets', 'ticket_sprints', ['sprint_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_index(op.f('ix_tickets_sprint_id'), table_name='tickets')
    op.drop_column('tickets', 'sprint_id')
    op.drop_index(op.f('ix_ticket_sprints_status'), table_name='ticket_sprints')
    op.drop_index(op.f('ix_ticket_sprints_project_id'), table_name='ticket_sprints')
    op.drop_index(op.f('ix_ticket_sprints_id'), table_name='ticket_sprints')
    op.drop_index(op.f('ix_ticket_sprints_company_id'), table_name='ticket_sprints')
    op.drop_table('ticket_sprints')
    # ### end Alembic commands ###
