"""reopen status tracking columns added

Revision ID: d54262e37501
Revises: 06bc94628aea
Create Date: 2025-10-28 01:01:00.858653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd54262e37501'
down_revision: Union[str, Sequence[str], None] = '06bc94628aea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add reopen_count with server_default to handle existing rows
    op.add_column('conversation_sessions', sa.Column('reopen_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('conversation_sessions', sa.Column('last_reopened_at', sa.DateTime(), nullable=True))
    op.add_column('conversation_sessions', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_sessions', 'resolved_at')
    op.drop_column('conversation_sessions', 'last_reopened_at')
    op.drop_column('conversation_sessions', 'reopen_count')
    # ### end Alembic commands ###
