"""Add vision_enabled to agents

Revision ID: e893a4f04f51
Revises: 607d3abad39f
Create Date: 2025-12-17 20:06:59.129754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e893a4f04f51'
down_revision: Union[str, Sequence[str], None] = '607d3abad39f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('vision_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'vision_enabled')
    # ### end Alembic commands ###
