"""add_entity_notes_table

Revision ID: eac8b54e3676
Revises: f7676a152ce5
Create Date: 2025-12-06 17:37:43.802916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eac8b54e3676'
down_revision: Union[str, Sequence[str], None] = 'f7676a152ce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('note_type', sa.Enum('NOTE', 'CALL', 'MEETING', 'EMAIL', 'TASK', name='notetype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('activity_date', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('participants', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('outcome', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_notes_company_id'), 'entity_notes', ['company_id'], unique=False)
    op.create_index(op.f('ix_entity_notes_contact_id'), 'entity_notes', ['contact_id'], unique=False)
    op.create_index(op.f('ix_entity_notes_created_by'), 'entity_notes', ['created_by'], unique=False)
    op.create_index(op.f('ix_entity_notes_id'), 'entity_notes', ['id'], unique=False)
    op.create_index(op.f('ix_entity_notes_lead_id'), 'entity_notes', ['lead_id'], unique=False)
    op.create_index(op.f('ix_entity_notes_note_type'), 'entity_notes', ['note_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entity_notes_note_type'), table_name='entity_notes')
    op.drop_index(op.f('ix_entity_notes_lead_id'), table_name='entity_notes')
    op.drop_index(op.f('ix_entity_notes_id'), table_name='entity_notes')
    op.drop_index(op.f('ix_entity_notes_created_by'), table_name='entity_notes')
    op.drop_index(op.f('ix_entity_notes_contact_id'), table_name='entity_notes')
    op.drop_index(op.f('ix_entity_notes_company_id'), table_name='entity_notes')
    op.drop_table('entity_notes')
    op.execute('DROP TYPE IF EXISTS notetype')
    # ### end Alembic commands ###
