"""Add handoff fields and agent pool

Revision ID: efb472d9be62
Revises: 8c3f1a2d5e6b
Create Date: 2025-11-14 21:37:31.087092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efb472d9be62'
down_revision: Union[str, Sequence[str], None] = '8c3f1a2d5e6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create agent_pools table
    op.create_table('agent_pools',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('pool_name', sa.String(), nullable=False),
        sa.Column('priority', sa.Integer(), nullable=True, server_default='0'),
        sa.Column('is_available', sa.Boolean(), nullable=True, server_default='true'),
        sa.Column('max_concurrent_sessions', sa.Integer(), nullable=True, server_default='3'),
        sa.Column('current_session_count', sa.Integer(), nullable=True, server_default='0'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_pools_id'), 'agent_pools', ['id'], unique=False)
    op.create_index(op.f('ix_agent_pools_user_id'), 'agent_pools', ['user_id'], unique=False)
    op.create_index(op.f('ix_agent_pools_company_id'), 'agent_pools', ['company_id'], unique=False)
    op.create_index(op.f('ix_agent_pools_pool_name'), 'agent_pools', ['pool_name'], unique=False)

    # Add handoff columns to conversation_sessions
    op.add_column('conversation_sessions', sa.Column('handoff_requested_at', sa.DateTime(), nullable=True))
    op.add_column('conversation_sessions', sa.Column('handoff_reason', sa.String(), nullable=True))
    op.add_column('conversation_sessions', sa.Column('assigned_pool', sa.String(), nullable=True))
    op.add_column('conversation_sessions', sa.Column('waiting_for_agent', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('conversation_sessions', sa.Column('handoff_accepted_at', sa.DateTime(), nullable=True))
    op.alter_column('video_calls', 'timeout_seconds',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('30'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video_calls', 'timeout_seconds',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('30'))

    # Drop handoff columns from conversation_sessions
    op.drop_column('conversation_sessions', 'handoff_accepted_at')
    op.drop_column('conversation_sessions', 'waiting_for_agent')
    op.drop_column('conversation_sessions', 'assigned_pool')
    op.drop_column('conversation_sessions', 'handoff_reason')
    op.drop_column('conversation_sessions', 'handoff_requested_at')

    # Drop agent_pools table
    op.drop_index(op.f('ix_agent_pools_pool_name'), table_name='agent_pools')
    op.drop_index(op.f('ix_agent_pools_company_id'), table_name='agent_pools')
    op.drop_index(op.f('ix_agent_pools_user_id'), table_name='agent_pools')
    op.drop_index(op.f('ix_agent_pools_id'), table_name='agent_pools')
    op.drop_table('agent_pools')
    # ### end Alembic commands ###
