"""add_message_templates_table

Revision ID: f6925f987f5e
Revises: eac8b54e3676
Create Date: 2025-12-10 16:46:37.412195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6925f987f5e'
down_revision: Union[str, Sequence[str], None] = 'eac8b54e3676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('shortcut', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('scope', sa.Enum('PERSONAL', 'SHARED', name='templatescope'), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_templates_company_id'), 'message_templates', ['company_id'], unique=False)
    op.create_index(op.f('ix_message_templates_created_by_user_id'), 'message_templates', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_message_templates_id'), 'message_templates', ['id'], unique=False)
    op.create_index(op.f('ix_message_templates_scope'), 'message_templates', ['scope'], unique=False)
    op.create_index(op.f('ix_message_templates_shortcut'), 'message_templates', ['shortcut'], unique=False)
    op.drop_constraint(op.f('fk_campaign_messages_template_id'), 'campaign_messages', type_='foreignkey')
    op.create_foreign_key(None, 'campaign_messages', 'templates', ['template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'campaign_messages', type_='foreignkey')
    op.create_foreign_key(op.f('fk_campaign_messages_template_id'), 'campaign_messages', 'templates', ['template_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_message_templates_shortcut'), table_name='message_templates')
    op.drop_index(op.f('ix_message_templates_scope'), table_name='message_templates')
    op.drop_index(op.f('ix_message_templates_id'), table_name='message_templates')
    op.drop_index(op.f('ix_message_templates_created_by_user_id'), table_name='message_templates')
    op.drop_index(op.f('ix_message_templates_company_id'), table_name='message_templates')
    op.drop_table('message_templates')
    # ### end Alembic commands ###
