"""add_transition_post_actions

Revision ID: fa04c105ca5d
Revises: ceaff61e3fda
Create Date: 2026-05-09 00:31:07.032081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa04c105ca5d'
down_revision: Union[str, Sequence[str], None] = 'ceaff61e3fda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_transitions', sa.Column('post_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_transitions', 'post_actions')
    # ### end Alembic commands ###
