"""add_workflow_triggers_table_auto

Revision ID: fb3f8bb1e576
Revises: 2426d72552f6
Create Date: 2025-10-20 01:02:50.395530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb3f8bb1e576'
down_revision: Union[str, Sequence[str], None] = '2426d72552f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_triggers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('WEBSOCKET', 'WHATSAPP', 'TELEGRAM', 'INSTAGRAM', name='triggerchannel'), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('fallback_agent_id', sa.Integer(), nullable=True),
    sa.Column('auto_respond', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['fallback_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_triggers_channel'), 'workflow_triggers', ['channel'], unique=False)
    op.create_index(op.f('ix_workflow_triggers_id'), 'workflow_triggers', ['id'], unique=False)
    op.drop_index(op.f('ix_optimization_suggestions_id'), table_name='optimization_suggestions')
    op.drop_table('optimization_suggestions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('optimization_suggestions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('suggestion_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('optimization_suggestions_agent_id_fkey')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('optimization_suggestions_company_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('optimization_suggestions_pkey'))
    )
    op.create_index(op.f('ix_optimization_suggestions_id'), 'optimization_suggestions', ['id'], unique=False)
    op.drop_index(op.f('ix_workflow_triggers_id'), table_name='workflow_triggers')
    op.drop_index(op.f('ix_workflow_triggers_channel'), table_name='workflow_triggers')
    op.drop_table('workflow_triggers')
    # ### end Alembic commands ###
