"""add_social_fields_to_contacts

Revision ID: fd40fd823124
Revises: 784d7abf9112
Create Date: 2026-03-28 16:34:34.012589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd40fd823124'
down_revision: Union[str, Sequence[str], None] = '784d7abf9112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('linkedin_url', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('linkedin_urn', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('instagram_handle', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('facebook_url', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('job_title', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('company_name', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('industry', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('location', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('website', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('enriched_at', sa.DateTime(), nullable=True))
    op.add_column('contacts', sa.Column('enrichment_source', sa.String(), nullable=True))
    op.create_index(op.f('ix_contacts_company_name'), 'contacts', ['company_name'], unique=False)
    op.create_index(op.f('ix_contacts_industry'), 'contacts', ['industry'], unique=False)
    op.create_index(op.f('ix_contacts_job_title'), 'contacts', ['job_title'], unique=False)
    op.create_index(op.f('ix_contacts_linkedin_url'), 'contacts', ['linkedin_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contacts_linkedin_url'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_job_title'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_industry'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_company_name'), table_name='contacts')
    op.drop_column('contacts', 'enrichment_source')
    op.drop_column('contacts', 'enriched_at')
    op.drop_column('contacts', 'website')
    op.drop_column('contacts', 'location')
    op.drop_column('contacts', 'industry')
    op.drop_column('contacts', 'company_name')
    op.drop_column('contacts', 'job_title')
    op.drop_column('contacts', 'facebook_url')
    op.drop_column('contacts', 'instagram_handle')
    op.drop_column('contacts', 'linkedin_urn')
    op.drop_column('contacts', 'linkedin_url')
    # ### end Alembic commands ###
